name: "CI"

on: {push: {branches: ['**']}, pull_request: {branches: [dev, master]}}

jobs:
  build:
    name: ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.image }}

    strategy:
      matrix:
        os:
          - {image: ubuntu-latest, name: Linux}
          - {image: windows-latest, name: Windows}
          - {image: macos-latest, name: macOS}
      max-parallel: 4
      fail-fast: false

    steps:
      - uses: "actions/checkout@main"
      - uses: "actions/setup-python@main"
        with:
          python-version: |
            3
            3.9
            3.10
            3.11
      - name: "Install dependencies"
        run: |
          python -mpip install --progress-bar=off nox
          python --version
          pip --version
          nox --version
      - name: "Run custom checks"
        run: "python -m nox -s check"
        env:
          PLATFORM: ${{ matrix.os.image }}
      - name: "Check with `black`"
        run: "python -m nox -s black"
        env:
          PLATFORM: ${{ matrix.os.image }}
      - name: "Check with `flake8`"
        run: "python -m nox -s flake8"
        env:
          PLATFORM: ${{ matrix.os.image }}
      - name: "Check with `isort`"
        run: "python -m nox -s isort"
        env:
          PLATFORM: ${{ matrix.os.image }}
      - name: "Build and check for packaging errors"
        run: "python -m nox -s build"
        env:
          PLATFORM: ${{ matrix.os.image }}
      - name: "Install the package"
        run: "python -m nox -s install"
        env:
          PLATFORM: ${{ matrix.os.image }}
